<../config.mk

<|bin/prereqs
results/%.count:
	set -x
	DIR_RESULTS="`dirname $target`"
	mkdir -p $DIR_RESULTS
	FILES=`bin/which-count-belong-sample $stem`	
	awk -F '\t' '{total += $1} END {printf("%d\n", total)}' $FILES \
		> $target'.build' \
		&& mv $target'.build' $target 	

